### ISSUE TITLE
Strange MBIS charges for molecules with Iodine when using DDX and def2-TZVPPD basis

### ISSUE THREAD

**Issue by jthorton** [psi4/psi4#3135]
For the below molecule I get very strange MBIS charges with the combination of DDX implicit solvent and the `def2-TZVPPD` basis set compared to using `def2-TZVP`.  I also only see this happen for molecules containing Iodine.
```python
from qcelemental.models.common_models import Model
from qcelemental.models import AtomicInput, Molecule
import qcengine
import numpy

qc_mol = Molecule.from_data(
    """
    0 1
    C                    -2.770566610000     0.138041700000     0.070178320000
    C                    -1.574766790000    -2.182402580000     0.041630990000
    C                     1.033304570000    -2.323434390000    -0.024422900000
    C                     2.435037490000    -0.121299970000    -0.061679550000
    C                     1.259017560000     2.209348470000    -0.033641890000
    C                    -1.350150920000     2.328080550000     0.032456990000
    I                     6.389923580000    -0.318582790000    -0.161855610000
    H                    -4.794725900000     0.238941070000     0.121450260000
    H                    -2.664958600000    -3.891956620000     0.070604800000
    H                     1.951364020000    -4.127647160000    -0.046322210000
    H                     2.351710440000     3.913369620000    -0.062674850000
    H                    -2.265188840000     4.137542080000     0.054275640000
    units bohr
    no_com
    no_reorient
    """
)
# create the psi4 job
spec = Model(method="PBE0", basis="def2-TZVPPD")
task = AtomicInput(
    molecule=qc_mol,
    driver="properties",
    keywords={
        "function_kwargs": {
            "properties": [
                # "dipole_polarizabilities",
                "mbis_charges",
                "quadrupole",
                "mulliken_charges",
                "dipole",
                "lowdin_charges",
                "wiberg_lowdin_indices",
                "mayer_indices",
            ]
        },
        "ddx": True,
        "ddx_model": "pcm",
        "ddx_solvent_epsilon": 4.0,
        "ddx_solvent": "water",
    },
    model=spec,
)
result = qcengine.compute(
    input_data=task, raise_error=True, task_config={"ncores": 4}, program="psi4"
)
print(result.extras["qcvars"]["MBIS CHARGES"])
```
`def2-TZVPPD`
> [[ 2.5896714 ]
 [ 0.9083468 ]
 [ 0.96984483]
 [ 1.82049044]
 [ 1.84275851]
 [ 1.27477756]
 [-0.33630084]
 [ 0.9999906 ]
 [-0.6920741 ]
 [-7.79483929]
 [-2.0360328 ]
 [ 0.45360942]]

`def2-TZVP`
>[[-0.14122935]
 [-0.13601096]
 [-0.12667168]
 [-0.07069663]
 [-0.12664356]
 [-0.13593726]
 [-0.05171043]
 [ 0.15172393]
 [ 0.15317262]
 [ 0.16536587]
 [ 0.16536188]
 [ 0.15326172]]

## conda output
```
# packages in environment at /Users/joshua/mambaforge/envs/qcsubmit-test-psi4:
#
# Name                    Version                   Build  Channel
psi4                      1.9             py311h5db8dd7_1    conda-forge
pyddx                     0.6.0           py311h6a48a4f_1    conda-forge
```

**Comment by JGrantHill** [comment]
Does the overall energy look sensible when you've got the additional diffuse functions? 

I occasionally find that def2-TZVPD converges to some odd state with strange properties (energy, dipole etc). I'd put it down to some form of numerical difficulties as I could usually use a mixed basis of def2-TZVP on some atoms and def2-TZVPD on others and get logical values (identity of which atoms to change was system dependent, but often H is the main culprit).

**Comment by susilehtola** [comment]
Which version are you using? IIRC older versions have had some issues with ECPs.

**Comment by bismuthadams1** [comment]
Currently we're using 
`pyddx                     0.6.0`
and 
`psi4                      1.8.1 `

To add to this issue further, a lot of my tests with def2-TZVPPD either a) fail to converge entirely or b) hang indefinitely.

**Comment by jthorton** [comment]
> To add to this issue further, a lot of my tests with def2-TZVPPD either a) fail to converge entirely or b) hang indefinitely.

I am also seeing this with psi4 1.9 as well.

**Comment by amcisaac** [comment]
I gave this a try (using Psi4 1.9.1) and noticed that the energy converged to a state ~20 hartrees below the def2-TZVP result. I think the def2-TZVP is the "correct" state as it converges to this state in vacuum and with PCMSolver using def2-TZVPPD, as well as using ddX with def2-TZVPP. 

I tried changing the guess to Huckel which seems to have resolved the issue for this particular case. I also tried changing the convergence algorithm (e.g. using damping, not using ADIIS, etc), as well as other guesses, but only the Huckel guess was able to converge to the same state as the def2-TZVP. 

I would think that the specific solution isn't necessarily transferrable to all other systems, but that fiddling with the convergence/guess settings may help in general.

Result:
```
  MBIS Charges: (a.u.)
   Center  Symbol  Z      Pop.       Charge
      1       C    6    6.139025   -0.139025
      2       C    6    6.133511   -0.133511
      3       C    6    6.122876   -0.122876
      4       C    6    6.070789   -0.070789
      5       C    6    6.122873   -0.122873
      6       C    6    6.133418   -0.133418
      7       I   25   25.053866   -0.053866
      8       H    1    0.850991    0.149009
      9       H    1    0.849569    0.150431
     10       H    1    0.836862    0.163138
     11       H    1    0.836785    0.163215
     12       H    1    0.849450    0.150550
```

Input:
```
molecule test {
    0 1
    C                    -2.770566610000     0.138041700000     0.070178320000
    C                    -1.574766790000    -2.182402580000     0.041630990000
    C                     1.033304570000    -2.323434390000    -0.024422900000
    C                     2.435037490000    -0.121299970000    -0.061679550000
    C                     1.259017560000     2.209348470000    -0.033641890000
    C                    -1.350150920000     2.328080550000     0.032456990000
    I                     6.389923580000    -0.318582790000    -0.161855610000
    H                    -4.794725900000     0.238941070000     0.121450260000
    H                    -2.664958600000    -3.891956620000     0.070604800000
    H                     1.951364020000    -4.127647160000    -0.046322210000
    H                     2.351710440000     3.913369620000    -0.062674850000
    H                    -2.265188840000     4.137542080000     0.054275640000
    units bohr
    no_com
    no_reorient
    }

set {
        basis def2-TZVPPD
        ddx true
        ddx_model pcm
        ddx_solvent_epsilon 4.0
        guess huckel
        }


energy('pbe0')
properties('pbe0',properties= ["mbis_charges","quadrupole","mulliken_charges","dipole","lowdin_charges","wiberg_lowdin_indices","mayer_indices", ])
```

**Comment by susilehtola** [comment]
Perhaps one can get it to converge to the right state by reading in a guess from the def2-TZVP basis, as well?

**Comment by amcisaac** [comment]
I just wanted to note that I've had this issue again, and this time I'm unable to fix it by changing the guess. I've seen it now with several molecules that don't contain I, so I don't think it's necessarily related to the ECP or I atom. PySCF had no issue with this example using either their conventional PCM or ddPCM modules, so I don't think it's an inherent issue with this basis.

Here's an example, this fails to converge to the "expected" answer with either the default settings or reading the vacuum wavefunction as a guess. 

No guess:
```
from qcelemental.models.common_models import Model
from qcelemental.models import AtomicInput, Molecule
import qcengine
import numpy

qc_mol = Molecule.from_data(
    """
    1 1
         C           -0.260042020000     0.885462630000    -1.159784510000  
         C           -0.088845540000     1.208129230000     1.696445160000  
         N           -0.815424450000     3.890690130000     2.392010950000  
         C            0.721496910000    -1.670643360000    -2.152443790000  
         C           -1.063549680000    -3.841420440000    -1.557776710000  
         O           -1.948096970000    -5.099106660000    -3.182663630000  
         O            1.029493160000    -1.398900900000    -4.725495590000  
         H           -2.189705850000     1.155308030000    -1.806092140000  
         H            0.894874330000     2.306678020000    -2.081542830000  
         H           -1.363017000000     0.001652010000     2.739108210000  
         H            1.809322310000     0.937803050000     2.399286530000  
         H           -0.721859200000     4.189879560000     4.278063110000  
         H           -2.598701020000     4.299216180000     1.837344180000  
         H            0.339726220000     5.162960950000     1.554139510000  
         H            2.524391750000    -2.097515210000    -1.247187970000  
         H           -1.472639020000    -4.216240700000     0.431691060000  
         H            0.318200660000    -2.817364330000    -5.576682870000  
    units bohr
    no_com
    no_reorient
    """
)
# create the psi4 job
spec = Model(method="PBE0", basis="def2-TZVPPD")
task = AtomicInput(
    molecule=qc_mol,
    driver="properties",
    keywords={
        "function_kwargs": {
            "properties": [
                # "dipole_polarizabilities",
                "mbis_charges",
                "quadrupole",
                "mulliken_charges",
                "dipole",
                "lowdin_charges",
                #"wiberg_lowdin_indices",
                #"mayer_indices",
            ]
        },
        "ddx": True,
        "ddx_model": "pcm",
        "ddx_solvent": "water",
        'ddx_radii_set': 'bondi',
        'ddx_radii_scaling': 1.2,
        'ddx_solvent_epsilon': 78.4,
    },
    model=spec,
)
result = qcengine.compute(
    input_data=task, raise_error=True, task_config={"ncores": 4}, program="psi4"
)
print(result.stdout)
```

Guess Read (Psi4 input file):
```
molecule test {
    1 1
         C           -0.260042020000     0.885462630000    -1.159784510000  
         C           -0.088845540000     1.208129230000     1.696445160000  
         N           -0.815424450000     3.890690130000     2.392010950000  
         C            0.721496910000    -1.670643360000    -2.152443790000  
         C           -1.063549680000    -3.841420440000    -1.557776710000  
         O           -1.948096970000    -5.099106660000    -3.182663630000  
         O            1.029493160000    -1.398900900000    -4.725495590000  
         H           -2.189705850000     1.155308030000    -1.806092140000  
         H            0.894874330000     2.306678020000    -2.081542830000  
         H           -1.363017000000     0.001652010000     2.739108210000  
         H            1.809322310000     0.937803050000     2.399286530000  
         H           -0.721859200000     4.189879560000     4.278063110000  
         H           -2.598701020000     4.299216180000     1.837344180000  
         H            0.339726220000     5.162960950000     1.554139510000  
         H            2.524391750000    -2.097515210000    -1.247187970000  
         H           -1.472639020000    -4.216240700000     0.431691060000  
         H            0.318200660000    -2.817364330000    -5.576682870000  
    units bohr
    no_com
    no_reorient
}
# create the psi4 job
set {
        basis def2-TZVPPD
        dft_radial_points 99
        dft_spherical_points 590
        maxiter 200
    }

e,wfn = energy('pbe0',return_wfn=True)

set {
        basis def2-TZVPPD
        ddx True
        ddx_model pcm
        ddx_solvent water
        ddx_solvent_epsilon 78.4
        maxiter 200
        guess read
        ddx_radii_set bondi
        ddx_radii_scaling 1.2
    }

properties('pbe0',properties= ["mbis_charges","quadrupole","mulliken_charges","dipole","lowdin_charges","wiberg_lowdin_indices","mayer_indices", ])
```

The vacuum energy is `-363.11142404607966`, whereas both PCM calculations converge to something around `-653.5` with unphysical MBIS (and Mulliken) charge results:
```
  MBIS Charges: (a.u.)                                       
   Center  Symbol  Z      Pop.       Charge                  
      1       C    6    1.926149    4.073851                 
      2       C    6    1.943924    4.056076                 
      3       N    7    1.982558    5.017442                 
      4       C    6    1.933209    4.066791                 
      5       C    6    1.957089    4.042911                 
      6       O    8    6.764062    1.235938                 
      7       O    8   14.772552   -6.772552                 
      8       H    1    8.534492   -7.534492                 
      9       H    1    4.599147   -3.599147                 
     10       H    1    6.329483   -5.329483                 
     11       H    1    1.995757   -0.995757                 
     12       H    1    0.000000    1.000000                 
     13       H    1    0.000000    1.000000                 
     14       H    1    0.000000    1.000000                 
     15       H    1    3.263884   -2.263884                 
     16       H    1    0.000000    1.000000                 
     17       H    1    0.000003    0.999997 
```

I've tried using different initial guesses, VDW radii, etc but nothing has helped.

**Comment by trevorgokey** [comment]
I was able to get the CHNO molecule to converge to something reasonable with pbe0/def2-TZVPPD/pcm by setting `dft_bs_radius_alpha 5.0`. Doing this with the I-containing molecule works partly, but I found that I was only able to get reasonable MBIS charges when switching to the LRC functional wb97x/def2-TZVPPD/pcm. Simply adding d3bj onto pbe0 did not seem to work. I was also able to reproduce the issue with multiple DFT methods; HF seemed "stable" other than some convergence issues.

**Comment by amcisaac** [comment]
FYI, in my large dataset, I was able to converge way more calculations to the correct state with @trevorgokey 's suggestion of `dft_bs_radius_alpha 5.0` and wb97x, but others still failed. Seems like there's no easy or universal fix to this issue from the user end

**Comment by jaclark5** [comment]
There is a comment in the Psi4 file [oeprop.cc](https://github.com/psi4/psi4/blob/b0a457663fc8eac46e0b9a2f10885528d47ed992/psi4/src/psi4/libmints/oeprop.cc#L1631) that says "MBIS is not supported for elements with atomic number greater than 36".

It was pointed out in #2728  2 years ago that the parameter table needs to be expanded to support Iodine.

**Comment by jthorton** [comment]
Good catch @jaclark5, I am confused about how we are still getting charges for Iodine though and not getting the error Pavan originally reported.

**Comment by amcisaac** [comment]
Is it confirmed that this is fixed in #3399? I think it's possible this was a DDX problem, since some of the molecules didn't contain non-covered MBIS elements, and it seems to also affect the SCF solution.

**Comment by jaclark5** [comment]
@amcisaac you're right #3399 doesn't fix this. It seems that MBIS charges were calculated using the number of valance electrons, so when ECPs were used, there were fewer electrons so a lower atomic number element was chosen for the MBIS calculation. That's why some molecules had weird charges and that's why molecules with iodine didn't always fail... the MBIS calculation treated them as a lighter element.

Unfortunately, ECPs are not compatible with MBIS charges according to a discussion on [denspart](https://github.com/theochem/denspart/issues/19), so the PR #3444 will prevent erroneous charges in the future by not allowing them.

**Comment by amcisaac** [comment]
Woof, OK, what a saga! Thanks for doing this investigation. 

I will see if my problematic, non-I-containing DDX inputs still give bad charges in the next release. If they do, I'll open a new issue that doesn't reference I to decouple these two discussions, since I do suspect this is (also?) a DDX bug.
